version: "3.7"

services:
  server:
    container_name: xiaou
    image: ncj/xiaou
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /xiaou/
    working_dir: /xiaou/
    environment:
      APP_ID:
      APP_KEY:
      APP_SECRET:
      DJANGO_SECRET_KEY:
      DB_HOST:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
    command: ./command.sh
