# Generated by Django 3.1.3 on 2020-11-25 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='问题内容')),
                ('reply_type', models.IntegerField(choices=[(0, '文本'), (1, '选项')], verbose_name='回复类型')),
                ('process_type', models.IntegerField(choices=[(0, '普通匹配'), (1, '感恩日志'), (2, '心情记录'), (3, '输入昵称')], verbose_name='处理类型')),
            ],
            options={
                'verbose_name': '问题模板',
                'verbose_name_plural': '问题模板',
            },
        ),
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False, verbose_name='已回答')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.questiontemplate', verbose_name='问题模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '问题记录',
                'verbose_name_plural': '问题记录',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', related_query_name='received_message', to=settings.AUTH_USER_MODEL, verbose_name='接收方')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', related_query_name='sent_message', to=settings.AUTH_USER_MODEL, verbose_name='发送方')),
            ],
            options={
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='选项内容')),
                ('reply_content', models.TextField(verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dest_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.questiontemplate', verbose_name='指向问题')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.questiontemplate', verbose_name='所属问题')),
            ],
            options={
                'verbose_name': '问题选项',
                'verbose_name_plural': '问题选项',
            },
        ),
    ]
