# Generated by Django 3.1.3 on 2020-11-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='root',
            field=models.BooleanField(default=False, verbose_name='根问题'),
        ),
    ]
