# Generated by Django 3.1.3 on 2020-11-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_questiontemplate_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='关键词')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.questiontemplate', verbose_name='所属问题')),
            ],
            options={
                'verbose_name': '匹配关键词',
                'verbose_name_plural': '匹配关键词',
            },
        ),
    ]
