# Generated by Django 3.1.3 on 2020-11-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
