# Generated by Django 3.1.3 on 2020-11-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='openid'),
        ),
    ]
