# Generated by Django 3.1.3 on 2020-11-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201123_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='openid'),
        ),
    ]
