# Generated by Django 3.1.3 on 2020-12-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201123_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_session_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='chat_session_id'),
        ),
    ]
