# Generated by Django 3.1.3 on 2020-11-23 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'smile'), (1, 'like'), (2, 'happy'), (3, 'upset'), (4, 'sad'), (5, 'angry'), (6, 'ok')], verbose_name='心情类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='心情描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '心情记录',
                'verbose_name_plural': '心情记录',
            },
        ),
    ]
