# Generated by Django 3.1.3 on 2020-11-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodrecord',
            name='type',
            field=models.IntegerField(choices=[(0, 'smile'), (1, 'like'), (2, 'happy'), (3, 'upset'), (4, 'sad'), (5, 'angry'), (6, 'ok'), (7, 'gratitude')], verbose_name='心情类型'),
        ),
    ]
