# Generated by Django 3.1.3 on 2020-12-16 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_config.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.JSONField(default=user_config.constants.toolbox_status_default, verbose_name='状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '工具箱状态',
                'verbose_name_plural': '工具箱状态',
            },
        ),
    ]
